packages:
  - src/web/
  - src/typespec/packages/*
  - src/typespec/core/packages/*
  - "!src/typespec/core/packages/website"
  - "!src/typespec/packages/website"
  - "!src/typespec/core/packages/http-client-csharp/**"
